### ISSUE TITLE
make create error.  

### ISSUE THREAD

**Issue by KriKri17** [xoe-labs/odooup#5]
/opt/odoo/./vendor/odoo/cc <- https://github.com/xoe-labs/odoo-dev/compare/12.0...xoe-labs:12.0-BACKPORT-BRANCH-add-odoo-redis-session-store.patch
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  9193    0  9193    0     0  26420      0 --:--:-- --:--:-- --:--:-- 26492
warning: unable to unlink /opt/odoo/./vendor/odoo/cc/odoo/http.py: Permission denied
warning: unable to unlink /opt/odoo/./vendor/odoo/cc/odoo/tools/config.py: Permission denied
error: unable to write file '/opt/odoo/./vendor/odoo/cc/odoo/http.py' mode 100644: Permission denied

**Comment by blaggacao** [comment]
Could you share the full logs in a gist?

The expected sequence is:
- `make create` does apply the patches within docker container.
- `make patch` does bind mount the host files in RW mode to patch the host files, too.

First I need to understand (with the logs) which one is actually failing.

Furthemore:
- What operating system are you on?
- What docker version do you have?
- Do you have any special security groups related setup? -> see COMPOSE_IMPERSONATION env variable.

**Comment by yelizariev** [comment]
> What operating system are you on?

It's lxd container with ``security.privileged`` set to true. All commands are run from container's root. 

COMPOSE_IMPERSONATION is not set. Is it supposed to have some value there?

**Comment by KriKri17** [comment]
https://gist.github.com/KriKri17/671d2f147d69c49633dd11b2ac846181
https://gist.github.com/KriKri17/96b96679c33586803361e3b0096ab95a

**Comment by KriKri17** [comment]
Docker version 18.09.2, build 6247962

**Comment by blaggacao** [comment]
> https://gist.github.com/KriKri17/671d2f147d69c49633dd11b2ac846181
> https://gist.github.com/KriKri17/96b96679c33586803361e3b0096ab95a

`/opt/odoo` is the folder of your project? I mean `ls -la /opt/odoo` looks something like this:
```bash
total 292
drwxrwxr-x  8 blaggacao blaggacao  4096 May 14 23:37 .
drwxrwxrwx 29 blaggacao blaggacao  4096 May  5 03:45 ..
-rw-rw-r--  1 blaggacao blaggacao    23 Nov  7  2018 .adminpwd
drwxrwxr-x  2 blaggacao blaggacao  4096 May 14 23:37 cfg.d
-rw-rw-r--  1 blaggacao blaggacao   511 May  5 02:00 docker-compose.override.yml
-rw-rw-r--  1 blaggacao blaggacao  4073 May 14 23:37 docker-compose.yml
-rw-rw-r--  1 blaggacao blaggacao   189 May  2 10:19 Dockerfile
-rw-rw-r--  1 blaggacao blaggacao   152 Nov  8  2018 .dockerignore
-rw-r--r--  1 blaggacao blaggacao   457 Mar  3 10:21 .editorconfig
-rw-rw-r--  1 blaggacao blaggacao   224 May  2 10:19 .env
-rw-rw-r--  1 blaggacao blaggacao   435 May  5 14:28 .flake8
drwxrwxrwx 10 blaggacao blaggacao  4096 May 14 23:37 .git
-rw-rw-r--  1 blaggacao blaggacao   965 Nov  8  2018 .gitignore
-rw-rw-r--  1 blaggacao blaggacao  5069 May  3 19:15 .gitlab-ci.setup.yml
-rw-r--r--  1 blaggacao blaggacao  1056 Mar  4 10:06 .gitlab-ci.yml
-rw-rw-r--  1 blaggacao blaggacao   311 May 13 22:53 .gitmodules
-rw-rw-r--  1 blaggacao blaggacao   248 May  2 12:25 .isort.cfg
-rw-rw-r--  1 blaggacao blaggacao  7651 Nov  8  2018 LICENSE
-rw-rw-r--  1 blaggacao blaggacao  5971 May  2 10:19 Makefile
drwxrwxr-x  2 blaggacao blaggacao  4096 May 13 22:53 migration.d
-rw-rw-r--  1 blaggacao blaggacao  1205 May 14 23:37 migration.yaml
drwxrwxr-x  2 blaggacao blaggacao  4096 May  2 10:19 patches.d
-rw-r--r--  1 blaggacao blaggacao  1210 May  5 15:01 .pre-commit-config.yaml
-rw-rw-r--  1 blaggacao blaggacao 14848 May  5 15:08 .pylintrc
-rw-rw-r--  1 blaggacao blaggacao   135 Nov  8  2018 README.md
drwxrwxrwx 20 blaggacao blaggacao 12288 May 14 21:30 src
drwxr-xr-x  7 blaggacao blaggacao  4096 May 13 15:50 vendor
```

Can you confirm?

**Comment by blaggacao** [comment]
> It's lxd container with `security.privileged` set to true. All commands are run from container's root.
> 
> COMPOSE_IMPERSONATION is not set. Is it supposed to have some value there?

I guess it `lxc` can be assumed unsupported (or at least untested). Could you test in a standard linux (eg ubuntu)?

Yes,  https://github.com/xoe-labs/odooup/blob/09d54813682fbde5a31746ed8a99368f9869f8d1/odooup/_installers.py#L33-L59

That might also be the root cause, see:
```python
    if platform.system() != "Linux":
        # Docker for X does handle user mapping for us
        return
```

**Comment by blaggacao** [comment]
AFAIK MacOs and Windows handle user impersonation through their VM abstraction layer. Could not test it, though.

**Comment by yelizariev** [comment]
System is linux inside lxc
```

>>> platform.system()
'Linux'

```

**Comment by yelizariev** [comment]
> I would have expected something like /tmp/my-client-project /opt/odoo is the internal naming of the docker containers. Or is it just coincidence?

``/opt/odoo`` is a folder where we run ``make ...``. 


```
root@KriKri17:/opt/odoo# ls -la
total 132
drwxr-xr-x 8 root root  4096 May 15 12:43 .
drwxr-xr-x 4 root root  4096 May 15 13:17 ..
-rw-r--r-- 1 root root    23 May 15 12:43 .adminpwd
-rw-r--r-- 1 root root   152 May 15 12:43 .dockerignore
-rw-r--r-- 1 root root   457 May 15 12:43 .editorconfig
-rw-r--r-- 1 root root   212 May 15 12:43 .env
-rw-r--r-- 1 root root   435 May 15 12:43 .flake8
drwxr-xr-x 8 root root  4096 May 15 12:43 .git
-rw-r--r-- 1 root root   965 May 15 12:43 .gitignore
-rw-r--r-- 1 root root  5069 May 15 12:43 .gitlab-ci.setup.yml
-rw-r--r-- 1 root root  1011 May 15 12:43 .gitlab-ci.yml
-rw-r--r-- 1 root root   308 May 15 12:43 .gitmodules
-rw-r--r-- 1 root root   133 May 15 12:43 .isort.cfg
-rw-r--r-- 1 root root  1210 May 15 12:43 .pre-commit-config.yaml
-rw-r--r-- 1 root root 14848 May 15 12:43 .pylintrc
-rw-r--r-- 1 root root   189 May 15 12:43 Dockerfile
-rw-r--r-- 1 root root  7651 May 15 12:43 LICENSE
-rw-r--r-- 1 root root  5971 May 15 12:43 Makefile
-rw-r--r-- 1 root root   135 May 15 12:43 README.md
drwxr-xr-x 2 root root  4096 May 15 12:43 cfg.d
-rw-r--r-- 1 root root   477 May 15 12:43 docker-compose.override.yml
-rw-r--r-- 1 root root  3814 May 15 12:43 docker-compose.yml
drwxr-xr-x 2 root root  4096 May 15 12:43 migration.d
-rw-r--r-- 1 root root   552 May 15 12:43 migration.yaml
drwxr-xr-x 2 root root  4096 May 15 12:43 patches.d
drwxr-xr-x 2 root root  4096 May 15 12:43 src
drwxr-xr-x 6 root root  4096 May 15 12:43 vendor

```

**Comment by yelizariev** [comment]
@KriKri17 has only windows with WSL and lxc container ¯ \ _ (ツ) _ / ¯.

**Comment by blaggacao** [comment]
I'm pretty sure it's because the COMPOSE_IMPERSONATION doesn't get setup properly. So the user impersonation doesn't work.

Could you check?

**Comment by yelizariev** [comment]
```
root@KriKri17:~# python
Python 2.7.12 (default, Nov 12 2018, 14:36:49) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> compose_impersonation = "{}:{}".format(os.getuid(), os.getgid()) 
>>> compose_impersonation
'0:0'

```

Does it explain something?

**Comment by yelizariev** [comment]
I think we saw message *about COMPOSE_IMPERSONATION* somewhere in logs :thinking:

**Comment by blaggacao** [comment]
> ```
> root@KriKri17:~# python
> Python 2.7.12 (default, Nov 12 2018, 14:36:49) 
> [GCC 5.4.0 20160609] on linux2
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import os
> >>> compose_impersonation = "{}:{}".format(os.getuid(), os.getgid()) 
> >>> compose_impersonation
> '0:0'
> ```
> 
> Does it explain something?

Looks ok.

Also check `os.path.realpath(os.path.expanduser("~/.bashrc")`
and above all, if `~/.bashrc` is actually sourced by this particular linux distribution / setup.

**Comment by blaggacao** [comment]
For scaffold, we need to write to host:
https://github.com/xoe-labs/dockery-odoo-scaffold/blob/master/docker-compose.yml#L100
For patches, we need to write to host:
https://github.com/xoe-labs/dockery-odoo-scaffold/blob/master/docker-compose.yml#L153

docker-compose takes those variables, either from the `.env` file or directly form the environment.
As `.env` is version controlled, we need a place to persist it on the user's host environment.

I chose `~/.bashrc`.

**Comment by yelizariev** [comment]
```
root@KriKri17:~# python
Python 2.7.12 (default, Nov 12 2018, 14:36:49) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.path.realpath(os.path.expanduser("~/.bashrc")
... )
'/root/.bashrc'
>>> 
```

Actually, the variable is set:

```
root@KriKri17:~# tail /root/.bashrc 
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
#if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
#    . /etc/bash_completion
#fi

export COMPOSE_IMPERSONATION='0:0'

```

**Comment by yelizariev** [comment]
Do the scripts run some code from another user?

**Comment by blaggacao** [comment]
> Do the scripts run some code from another user?

No.
If, at runtime, it's not in the environment, that would mean that `/root/.bashrc` is not loadad?

**Comment by yelizariev** [comment]
``env`` says that the variable is set... I tried to run ``make info`` again it got new error

```
failed to update store for object type *libnetwork.endpointCnt: Key not found in store
Makefile:79: recipe for target 'build-base' failed
make[1]: *** [build-base] Error 1
make[1]: Leaving directory '/opt/odoo'
Makefile:127: recipe for target 'info' failed
make: *** [info] Error 2

```

**Comment by blaggacao** [comment]
`libnetwork.endpointCnt` What? :-D

**Comment by yelizariev** [comment]
I added ``--exec-driver=lxc`` as described here https://stackoverflow.com/questions/22085657/can-docker-run-inside-a-linux-container and that ``libnetwork.endpointCnt`` error is gone. But patching still shows some errors:

```

/opt/odoo/./vendor/odoo/cc <- https://patch-diff.githubusercontent.com/raw/odoo/odoo/pull/26480.patch
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1069    0  1069    0     0   2009      0 --:--:-- --:--:-- --:--:--  2009
error: patch failed: /opt/odoo/./vendor/odoo/cc/odoo/cli/scaffold.py:45
error: /opt/odoo/./vendor/odoo/cc/odoo/cli/scaffold.py: patch does not apply
File: /opt/odoo/patches.d/001-redis-session-store.url

/opt/odoo/./vendor/odoo/cc <- https://github.com/xoe-labs/odoo-dev/compare/12.0...xoe-labs:12.0-BACKPORT-BRANCH-add-odoo-redis-session-store.patch
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  9193    0  9193    0     0  12413      0 --:--:-- --:--:-- --:--:-- 12406
error: patch failed: /opt/odoo/./vendor/odoo/cc/odoo/http.py:44
error: /opt/odoo/./vendor/odoo/cc/odoo/http.py: patch does not apply
error: /opt/odoo/./vendor/odoo/cc/odoo/session.py: already exists in working directory
error: patch failed: /opt/odoo/./vendor/odoo/cc/odoo/tools/config.py:137
error: /opt/odoo/./vendor/odoo/cc/odoo/tools/config.py: patch does not apply

```

**Comment by yelizariev** [comment]
Well, Postgres actually works now. Patch errors may be due to applying them against already patched files

**Comment by yelizariev** [comment]
It all looks strange. But it works. I don't know why we got permission errors at the beginning

**Comment by yelizariev** [comment]
Can be closed

**Comment by blaggacao** [comment]
> Well, Postgres actually works now. Patch errors may be due to applying them against already patched files

You actually can tell the difference from the logs. But yes, it usually fails once the patches are already baked into the container...
