### ISSUE TITLE
Git version checking

### ISSUE THREAD

**Issue by em230418** [xoe-labs/odooup#8]
After running:
```
odooup init project
cd project
make info
make run
```
I receive this:
```
odoo_1           | /entrypoint.sh: line 80: /opt/odoo/vendor/odoo/cc/odoo-bin: No such file or directory
project_odoo_1 exited with code 127
```

After investigating I made a conclusion, that this command:
```git submodule add -b 12.0 --reference /home/ubuntu/.cache/odooup/github.com/odoo/odoo --dissociate https://github.com/odoo/odoo.git ./vendor/odoo/cc```
prints help message instead of cloning

Reason is I have git version of 2.7.4 (ubuntu 16.04) which does not support `--dissociate` param for submodule command.

Checked git documentation, and found out that `--dissociate` works in [2.18.0](https://git-scm.com/docs/git-submodule/2.18.0#git-submodule---dissociate), and does not work in [2.16.4](https://git-scm.com/docs/git-submodule/2.16.4)

So I compiled 2.18.1 and was able to run odoo after `make run`

**Comment by blaggacao** [comment]
@em230418 Good idea. I'd even check vor v2.22 - Do you want to prepare a PR?

**Comment by em230418** [comment]
> Do you want to prepare a PR?

Currently busy with other project. Maybe next week

**Comment by yelizariev** [comment]
Here is how to update git
https://stackoverflow.com/questions/19109542/installing-latest-version-of-git-in-ubuntu

```
sudo add-apt-repository ppa:git-core/ppa
sudo apt-get update
sudo apt-get install git
```

**Comment by blaggacao** [comment]
it could go here: https://github.com/xoe-labs/odooup/blob/master/odooup/_installers.py#L63-L69

**Comment by blaggacao** [comment]
There are other checks which we can perform, too.

**Comment by em230418** [comment]
Looks like it fixed https://github.com/xoe-labs/odooup/commit/5744743982fedc5a754a8a23c54ce55e51b1bf13. Thanks @blaggacao
